server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8191/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8188/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-auth
            - JwtAuthFilter
        - id: recommends-service
          uri: http://localhost:8195/
          predicates:
            - Path=/recommends/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-recommends
            - JwtAuthFilter

jwt:
  secret: fgdffvdbvdt34t432r34rde3rr34r34r3f34f3

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
